import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate } from 'k6/metrics';
import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000';

const errorRate = new Rate('errors');

export const options = {
  thresholds: {
    http_req_duration: ['p(95)<500'], // 95% under 500ms
    http_req_failed: ['rate<0.01'],   // <1% errors
    errors: ['rate<0.01'],
  },
  stages: [
    { duration: '30s', target: 5 },   // ramp up
    { duration: '1m', target: 10 },   // steady load
    { duration: '20s', target: 0 },     // ramp down
  ],
};

function assert(response, checks) {
  const ok = check(response, checks);
  if (!ok) errorRate.add(1);
  return ok;
}

export default function () {
  const key = `key-${uuidv4()}`;
  const title = `Load test note ${uuidv4()}`;
  const content = `Content generated by k6 at ${Date.now()}`;

  let noteId;

  group('create note', () => {
    const res = http.post(
      `${BASE_URL}$/notes`,
      JSON.stringify({ title, content, key }),
      { headers: { 'Content-Type': 'application/json' } },
    );

    assert(res, {
      'create status is 201': (r) => r.status === 201,
      'create returns noteId': (r) => {
        const body = safeJson(r);
        return body && typeof body.noteId === 'string';
      },
    });

    if (res.status === 201) {
      noteId = safeJson(res).noteId;
    }
  });

  if (noteId) {
    group('reveal note', () => {
      const res = http.post(
        `${BASE_URL}$/notes/${noteId}/reveal`,
        JSON.stringify({ key }),
        { headers: { 'Content-Type': 'application/json' } },
      );

      assert(res, {
        'reveal status is 200': (r) => r.status === 200,
        'reveal returns content': (r) => {
          const body = safeJson(r);
          return body && body.content === content;
        },
      });
    });

    group('reveal with wrong key', () => {
      const res = http.post(
        `${BASE_URL}$/notes/${noteId}/reveal`,
        JSON.stringify({ key: 'wrong-key' }),
        { headers: { 'Content-Type': 'application/json' } },
      );

      assert(res, {
        'wrong key returns 403': (r) => r.status === 403,
      });
    });
  }

  group('list notes', () => {
    const res = http.get(`${BASE_URL}$/notes`);

    assert(res, {
      'list status is 200': (r) => r.status === 200,
      'list returns array': (r) => Array.isArray(safeJson(r)),
    });
  });

  sleep(1);
}

function safeJson(response) {
  try {
    return response.json();
  } catch {
    return null;
  }
}
